 name: Docker Image CI
    2
    3 on:
    4   push:
    5     branches: [ "main" ]
    6   pull_request:
    7     branches: [ "main" ]
    8
    9 jobs:
   10   build_and_push:
   11     runs-on: ubuntu-latest
   12     steps:
   13       - name: Checkout repository
   14         uses: actions/checkout@v4
   15
   16       - name: Login to Docker Hub
   17         uses: docker/login-action@v2
   18         with:
   19           username: ${{ secrets.DOCKER_USERNAME }}
   20           password: ${{ secrets.DOCKER_PASSWORD }}
   21
   22       - name: Build and push Docker image
   23         run: |
   24           # Define el tamaño del modelo a construir. Puedes cambiar "1b" por "7b", etc.
   25           MODEL_VERSION=1b
   26
   27           # Crea una etiqueta de imagen única con tu usuario de Docker y la fecha.
   28           IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/gagoraoss:${MODEL_VERSION}-$(date +%s)
   29
   30           echo "Building and pushing image: $IMAGE_TAG"
   31
   32           # Construye la imagen pasándole el argumento MODEL_SIZE y la etiqueta.
   33           docker build . \
   34             --file Dockerfile \
   35             --build-arg MODEL_SIZE=${MODEL_VERSION} \
   36             --tag $IMAGE_TAG
   37
   38           # Sube la imagen a Docker Hub.
   39           docker push $IMAGE_TAG
